name: First workflow test

on:
  push:
    branches: [ main ]

jobs:
  first_test_job:
    name: First Test Job
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "Test step 1 echo"